Backend/config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :donations
  resources :donors
  resources :charities
  resources :administrators


  get '/donors/:id', to: 'donors#show'
  
  # Auth Routes
  post '/login' , to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/loggedin', to: 'application#logged'
  # get '/loggedin', to: 'users#current_user'
  # get '/logged', to: 'application#administration'
  delete 'logout', to: 'sessions#destroy'

  get '/images' , to: 'images#index'

  #CHARITY ROUTES
  put "/charities/approve/:id", to: "charities#approve"
  delete "/charities/reject/:id", to: "charities#reject"
  get '/charitydetails/:id', to: 'charities#show'
  get '/charities', to: 'charities#index'
  post '/charity/signup', to: 'charities#create'

  get 'beneficiaries', to: 'charities#beneficiaries'
  get 'charitydetails', to: 'charities#beneficiaries'
  post 'beneficiaries', to: 'charities#create_beneficiary'
  put 'beneficiaries/:beneficiary_id', to: 'charities#update_beneficiary'
  delete 'beneficiaries/:beneficiary_id', to: 'charities#destroy_beneficiary'


  #DONOR ROUTES
  post '/donor/signup', to: 'donors#create'
  get '/donor/signup', to: 'donors#new'

  post '/donor/login', to: 'donors#login'
  get '/charities', to: 'donors#charities'
  get '/charities/:id', to: 'donors#show_charity'
  post '/donations', to: 'donors#donate'
  post '/donations/automate', to: 'donors#automate_donation'
  post '/donations/cancel', to: 'donors#cancel_donation'
  get '/beneficiaries', to: 'donors#beneficiaries'
  post '/donations/paypal', to: 'donors#paypal'
  post '/donations/stripe', to: 'donors#stripe'

   # Administrator routes
   post '/administrator/login', to: 'administrators#login'
   get '/administrator/applications', to: 'administrators#applications'
   post '/administrator/applications/:id/approve', to: 'administrators#approve_application'
   post '/administrator/applications/:id/reject', to: 'administrators#reject_application'
   delete '/administrator/charities/:id', to: 'administrators#delete_charity'
   get '/charities/unapproved', to: 'charities#unapproved'
   get '/charities/approved', to: 'charities#approved'
   


   # Donations routes
   get '/donations', to: 'donations#index'
   post '/donations', to: 'donations#create'
   get '/donations/:id', to: 'donations#show'
   put '/donations/:id', to: 'donations#update'
   delete '/donations/:id', to: 'donations#destroy'

  #  Application Routes
  # Contact Us Form Route
  post "/contact-us", to: 'application#contact_us'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Backend/app/models/donation.rb
class Donation < ApplicationRecord

    belongs_to :donor
    belongs_to :charity

end

Backend/app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_donor

  def index
    @donations = Donation.all
    render json: @donations
  end

  def create
    @donation = Donation.new(donation_params)
    if @donation.save
      DonorNotifierMailer.send_donation_received_email(@donation).deliver
      CharityNotifierMailer.send_new_donation_received_email(@donation).deliver
      render json: @donation, status: :created
    else
      render json: @donation.errors, status: :unprocessable_entity
    end
  end

  def show
    @donation = Donation.find(params[:id])
    render json: @donation
  end

  def update
    @donation = Donation.find(params[:id])
    if @donation.update(donation_params)
      render json: @donation
    else
      render json: @donation.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
  end

  private

  def donation_params
    params.require(:donation).permit(:donation_amount, :anonymous, :charity_id, :donor_id)
  end
end

Backend/app/helpers/donations_helper.rb
module DonationsHelper
end

Backend/app/views/donations/_donation.html.erb
<div id="<%= dom_id donation %>">
  <p>
    <strong>Donation amount:</strong>
    <%= donation.donation_amount %>
  </p>

  <p>
    <strong>Anonymous:</strong>
    <%= donation.anonymous %>
  </p>

  <p>
    <strong>Charity:</strong>
    <%= donation.charity_id %>
  </p>

  <p>
    <strong>Donor:</strong>
    <%= donation.donor_id %>
  </p>

</div>

Backend/app/views/donations/_form.html.erb
<%= form_with(model: donation) do |form| %>
  <% if donation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
        <% donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :donation_amount, style: "display: block" %>
    <%= form.number_field :donation_amount %>
  </div>

  <div>
    <%= form.label :anonymous, style: "display: block" %>
    <%= form.check_box :anonymous %>
  </div>

  <div>
    <%= form.label :charity_id, style: "display: block" %>
    <%= form.number_field :charity_id %>
  </div>

  <div>
    <%= form.label :donor_id, style: "display: block" %>
    <%= form.number_field :donor_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Backend/app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Show this donation", @donation %> |
  <%= link_to "Back to donations", donations_path %>
</div>

Backend/app/views/donations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Donations</h1>

<div id="donations">
  <% @donations.each do |donation| %>
    <%= render donation %>
    <p>
      <%= link_to "Show this donation", donation %>
    </p>
  <% end %>
</div>

<%= link_to "New donation", new_donation_path %>

Backend/app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Back to donations", donations_path %>
</div>

Backend/app/views/donations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @donation %>

<div>
  <%= link_to "Edit this donation", edit_donation_path(@donation) %> |
  <%= link_to "Back to donations", donations_path %>

  <%= button_to "Destroy this donation", @donation, method: :delete %>
</div>