Backend/config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :donations
  resources :donors
  resources :charities
  resources :administrators


  get '/donors/:id', to: 'donors#show'
  
  # Auth Routes
  post '/login' , to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/loggedin', to: 'application#logged'
  # get '/loggedin', to: 'users#current_user'
  # get '/logged', to: 'application#administration'
  delete 'logout', to: 'sessions#destroy'

  get '/images' , to: 'images#index'

  #CHARITY ROUTES
  put "/charities/approve/:id", to: "charities#approve"
  delete "/charities/reject/:id", to: "charities#reject"
  get '/charitydetails/:id', to: 'charities#show'
  get '/charities', to: 'charities#index'
  post '/charity/signup', to: 'charities#create'

  get 'beneficiaries', to: 'charities#beneficiaries'
  get 'charitydetails', to: 'charities#beneficiaries'
  post 'beneficiaries', to: 'charities#create_beneficiary'
  put 'beneficiaries/:beneficiary_id', to: 'charities#update_beneficiary'
  delete 'beneficiaries/:beneficiary_id', to: 'charities#destroy_beneficiary'


  #DONOR ROUTES
  post '/donor/signup', to: 'donors#create'
  get '/donor/signup', to: 'donors#new'

  post '/donor/login', to: 'donors#login'
  get '/charities', to: 'donors#charities'
  get '/charities/:id', to: 'donors#show_charity'
  post '/donations', to: 'donors#donate'
  post '/donations/automate', to: 'donors#automate_donation'
  post '/donations/cancel', to: 'donors#cancel_donation'
  get '/beneficiaries', to: 'donors#beneficiaries'
  post '/donations/paypal', to: 'donors#paypal'
  post '/donations/stripe', to: 'donors#stripe'

   # Administrator routes
   post '/administrator/login', to: 'administrators#login'
   get '/administrator/applications', to: 'administrators#applications'
   post '/administrator/applications/:id/approve', to: 'administrators#approve_application'
   post '/administrator/applications/:id/reject', to: 'administrators#reject_application'
   delete '/administrator/charities/:id', to: 'administrators#delete_charity'
   get '/charities/unapproved', to: 'charities#unapproved'
   get '/charities/approved', to: 'charities#approved'
   


   # Donations routes
   get '/donations', to: 'donations#index'
   post '/donations', to: 'donations#create'
   get '/donations/:id', to: 'donations#show'
   put '/donations/:id', to: 'donations#update'
   delete '/donations/:id', to: 'donations#destroy'

  #  Application Routes
  # Contact Us Form Route
  post "/contact-us", to: 'application#contact_us'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Backend/app/models/administrator.rb
class Administrator < ApplicationRecord
    has_secure_password
    has_many :charities
end

Backend/app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :authorize_admin

  # POST /admin/login
  def login
    administrator = Administrator.find_by(email: params[:email])
    if Administrator && Administrator.authenticate(params[:password])
      token = JWT.encode({ administrator_id: Administrator.id }, Rails.application.secrets.secret_key_base, 'HS256')
      render json: { token: token }
    else
      render json: { error: 'Invalid email or password' }, status: :unprocessable_entity
    end
  end


  # GET /charity_applications
  def charity_applications
    @charity_applications = CharityApplication.all
    render json: @charity_applications
  end

  def unapproved
    @charities = Charity.where(approved: false)
    render json: @charities, status: :ok
  end
  def approved
  @charities = Charity.where(approved: true)
  render json: @charities, status: :ok
end

  # POST /charity_applications/:id/approve
  def approve_charity_application
    @charity_application = CharityApplication.find(params[:id])
    if @charity_application.update(approved: true)
      # send email to notify charity that their application has been approved
      render json: @charity_application
    else
      render json: {"error": "unable to approve application" }, status: :unprocessable_entity
    end
  end

  # POST /charity_applications/:id/reject
  def reject_charity_application
    @charity_application = CharityApplication.find(params[:id])
    if @charity_application.update(approved: false)
      # send email to notify charity that their application has been rejected
      render json: @charity_application
    else
      render json: {"error": "unable to reject application" }, status: :unprocessable_entity
    end
  end

  # DELETE /charities/:id
  def destroy_charity
    @charity = Charity.find(params[:id])
    @charity.destroy
    render json: {"message": "charity deleted successfully" }
  end

  private
    def authorize_administartor
      # check if the request is coming from an admin
      token = request.headers["Authorization"]&.split(" ")&.last
      begin
        decoded_token = JWT.decode(token, Rails.application.secrets.secret_key_base, true, algorithm: 'HS256')
        admin_id = decoded_token[0]["admin_id"]
        @current_admin = Admin.find(admin_id)
      rescue JWT::DecodeError
        render json: {"error": "invalid token" }, status: :unauthorized
      end
    end
end

Backend/app/helpers/administrators_helper.rb
module AdministratorsHelper
end

Backend/app/views/administrators/_administrator.html.erb
<div id="<%= dom_id administrator %>">
  <p>
    <strong>First name:</strong>
    <%= administrator.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= administrator.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= administrator.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= administrator.password %>
  </p>

</div>

Backend/app/views/administrators/_form.html.erb
<%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
        <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Backend/app/views/administrators/edit.html.erb
<h1>Editing administrator</h1>

<%= render "form", administrator: @administrator %>

<br>

<div>
  <%= link_to "Show this administrator", @administrator %> |
  <%= link_to "Back to administrators", administrators_path %>
</div>

Backend/app/views/administrators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Administrators</h1>

<div id="administrators">
  <% @administrators.each do |administrator| %>
    <%= render administrator %>
    <p>
      <%= link_to "Show this administrator", administrator %>
    </p>
  <% end %>
</div>

<%= link_to "New administrator", new_administrator_path %>

Backend/app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render "form", administrator: @administrator %>

<br>

<div>
  <%= link_to "Back to administrators", administrators_path %>
</div>

Backend/app/views/administrators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @administrator %>

<div>
  <%= link_to "Edit this administrator", edit_administrator_path(@administrator) %> |
  <%= link_to "Back to administrators", administrators_path %>

  <%= button_to "Destroy this administrator", @administrator, method: :delete %>
</div>