Backend/config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :donations
  resources :donors
  resources :charities
  resources :administrators


  get '/donors/:id', to: 'donors#show'
  
  # Auth Routes
  post '/login' , to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/loggedin', to: 'application#logged'
  # get '/loggedin', to: 'users#current_user'
  # get '/logged', to: 'application#administration'
  delete 'logout', to: 'sessions#destroy'

  get '/images' , to: 'images#index'

  #CHARITY ROUTES
  put "/charities/approve/:id", to: "charities#approve"
  delete "/charities/reject/:id", to: "charities#reject"
  get '/charitydetails/:id', to: 'charities#show'
  get '/charities', to: 'charities#index'
  post '/charity/signup', to: 'charities#create'

  get 'beneficiaries', to: 'charities#beneficiaries'
  get 'charitydetails', to: 'charities#beneficiaries'
  post 'beneficiaries', to: 'charities#create_beneficiary'
  put 'beneficiaries/:beneficiary_id', to: 'charities#update_beneficiary'
  delete 'beneficiaries/:beneficiary_id', to: 'charities#destroy_beneficiary'


  #DONOR ROUTES
  post '/donor/signup', to: 'donors#create'
  get '/donor/signup', to: 'donors#new'

  post '/donor/login', to: 'donors#login'
  get '/charities', to: 'donors#charities'
  get '/charities/:id', to: 'donors#show_charity'
  post '/donations', to: 'donors#donate'
  post '/donations/automate', to: 'donors#automate_donation'
  post '/donations/cancel', to: 'donors#cancel_donation'
  get '/beneficiaries', to: 'donors#beneficiaries'
  post '/donations/paypal', to: 'donors#paypal'
  post '/donations/stripe', to: 'donors#stripe'

   # Administrator routes
   post '/administrator/login', to: 'administrators#login'
   get '/administrator/applications', to: 'administrators#applications'
   post '/administrator/applications/:id/approve', to: 'administrators#approve_application'
   post '/administrator/applications/:id/reject', to: 'administrators#reject_application'
   delete '/administrator/charities/:id', to: 'administrators#delete_charity'
   get '/charities/unapproved', to: 'charities#unapproved'
   get '/charities/approved', to: 'charities#approved'
   


   # Donations routes
   get '/donations', to: 'donations#index'
   post '/donations', to: 'donations#create'
   get '/donations/:id', to: 'donations#show'
   put '/donations/:id', to: 'donations#update'
   delete '/donations/:id', to: 'donations#destroy'

  #  Application Routes
  # Contact Us Form Route
  post "/contact-us", to: 'application#contact_us'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Backend/app/models/charity.rb
class Charity < ApplicationRecord
    has_secure_password
    belongs_to :administrator

   has_many :donations
   has_many :donors, through: :donations
   has_many :beneficiaries

   def total_donated
    self.donations.sum{|donation| donation.donation_amount}
   end

end

Backend/app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  skip_before_action :authorize, only: [:index, :show, :create]
  

  def index
    @charities = Charity.all
    render json: @charities, status: :ok
  end

  def show
    @charity = Charity.includes(:administrator, :beneficiaries).find(params[:id])
    render json: @charity
  end
  
  def create
    @charity = Charity.new(charity_params)
    @charity.administrator_id = 1
    @charity.approved = false 
    
    if @charity.save
      AdministratorNotifierMailer.send_new_charity_application_email(@charity).deliver
      CharityNotifierMailer.send_application_received_email(@charity).deliver
      render json: @charity, status: :created, location: @charity
    else
      render json: @charity.errors, status: :unprocessable_entity
    end
  end

  # PUT /charities/:id
  def update
    @charity = Charity.find(params[:id])
    if @charity.update(charity_params)
      render json: @charity, status: :ok
    else
      render json: @charity.errors, status: :unprocessable_entity
    end
  end

  # PUT /charities/approve/:id
  def approve
    @charity = set_charity
    
    if @charity.update(charity_params)
      CharityNotifierMailer.send_application_approved_email(@charity).deliver
      render json: @charity, status: :accepted
    else
      render json: @charity.errors, status: :unprocessable_entity
    end    
  end

  # DELETE /charities/reject/:id
  def reject
    @charity = set_charity
    CharityNotifierMailer.send_application_rejected_email(@charity).deliver
    @charity.destroy
    head :no_content
  end

  # DELETE /charities/:id
  def destroy
    @charity = set_charity
    AdministratorNotifierMailer.send_charity_deletion_email(@charity).deliver
    CharityNotifierMailer.send_charity_deletion_notice(@charity).deliver
    @charity.destroy
    head :no_content
  end

  def beneficiaries
    @charity = Charity.find(params[:id])
    @beneficiaries = @charity.beneficiaries
    render json: @beneficiaries, status: :ok
  end

  def create_beneficiary
    @charity = Charity.find(params[:id])
    @beneficiary = @charity.beneficiaries.create(beneficiary_params)
    render json: @beneficiary, status: :created, location: @beneficiary
  end

  def update_beneficiary
    @charity = Charity.find(params[:id])
    @beneficiary = @charity.beneficiaries.find(params[:beneficiary_id])

    if @beneficiary.update(beneficiary_params)
      render json: @beneficiary, status: :ok
    else
      render json: @beneficiary.errors, status: :unprocessable_entity
    end
  end

  def destroy_beneficiary
    @charity = Charity.find(params[:id])
    @beneficiary = @charity.beneficiaries.find(params[:beneficiary_id])
    @beneficiary.destroy
    head :no_content
  end

  def items
    @charity = Charity.find(params[:id])
    @beneficiary = @charity.beneficiaries.find(params[:beneficiary_id])
    @items = @beneficiary.items
    render json: @items, status: :ok
  end

  def create_items
    @charity = Charity.find(params[:id])
    @beneficiary = @charity.beneficiaries.find(params[:beneficiary_id])
    @items = @beneficiary.items.create(items_params)
    render json: @items, status: :created, location: @items
  end

  def update_items
    @charity = Charity.find(params[:id])
    @beneficiary = @charity.beneficiaries.find(params[:beneficiary_id])
    @items = @beneficiary.items.find(params[:items_id])

    if @items.update(items_params)
      render json: @items, status: :ok
    else
      render json: @items.errors, status: :unprocessable_entity
    end
  end

  def destroy_items
    @charity = Charity.find(params[:id])
    @beneficiary = @charity.beneficiaries.find(params[:beneficiary_id])
    @items = @beneficiary.items.find(params[:items_id])
    @items.destroy
    head :no_content
  end

  private
  def set_charity
    @charity = Charity.find(params[:id])
  end

  def unapproved_charities
    @charities = Charity.where(approved: false)
    render json: @charities, status: :ok
  end

  def approved_charities
    @charities = Charity.where(approved: true)
    render json: @charities, status: :ok
  end

  def charity_params
    params.permit( :email, :password, :approved)
  end

  def beneficiary_params
    params.require(:beneficiary).permit(:name, :description)
  end

  def items_params
    params.require(:items).permit(:name, :description, :quantity)
  end
end

Backend/app/helpers/charities_helper.rb
module CharitiesHelper
end

Backend/app/views/charities/_charity.html.erb
<div id="<%= dom_id charity %>">
  <p>
    <strong>Name:</strong>
    <%= charity.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= charity.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= charity.password %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= charity.description %>
  </p>

  <p>
    <strong>Img url:</strong>
    <%= charity.img_url %>
  </p>

  <p>
    <strong>Goal amount:</strong>
    <%= charity.goal_amount %>
  </p>

  <p>
    <strong>Total donations:</strong>
    <%= charity.total_donations %>
  </p>

  <p>
    <strong>Admin:</strong>
    <%= charity.admin_id %>
  </p>

</div>

Backend/app/views/charities/_form.html.erb
<%= form_with(model: charity) do |form| %>
  <% if charity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
        <% charity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :img_url, style: "display: block" %>
    <%= form.text_field :img_url %>
  </div>

  <div>
    <%= form.label :goal_amount, style: "display: block" %>
    <%= form.number_field :goal_amount %>
  </div>

  <div>
    <%= form.label :total_donations, style: "display: block" %>
    <%= form.number_field :total_donations %>
  </div>

  <div>
    <%= form.label :admin_id, style: "display: block" %>
    <%= form.number_field :admin_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Backend/app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render "form", charity: @charity %>

<br>

<div>
  <%= link_to "Show this charity", @charity %> |
  <%= link_to "Back to charities", charities_path %>
</div>

Backend/app/views/charities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Charities</h1>

<div id="charities">
  <% @charities.each do |charity| %>
    <%= render charity %>
    <p>
      <%= link_to "Show this charity", charity %>
    </p>
  <% end %>
</div>

<%= link_to "New charity", new_charity_path %>

Backend/app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render "form", charity: @charity %>

<br>

<div>
  <%= link_to "Back to charities", charities_path %>
</div>

Backend/app/views/charities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @charity %>

<div>
  <%= link_to "Edit this charity", edit_charity_path(@charity) %> |
  <%= link_to "Back to charities", charities_path %>

  <%= button_to "Destroy this charity", @charity, method: :delete %>
</div>