Backend/config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :donations
  resources :donors
  resources :charities
  resources :administrators


  get '/donors/:id', to: 'donors#show'
  
  # Auth Routes
  post '/login' , to: 'session#create'
  delete '/logout', to: 'session#destroy'
  get '/loggedin', to: 'application#logged'
  # get '/loggedin', to: 'users#current_user'
  # get '/logged', to: 'application#administration'
  delete 'logout', to: 'sessions#destroy'

  get '/images' , to: 'images#index'

  #CHARITY ROUTES
  put "/charities/approve/:id", to: "charities#approve"
  delete "/charities/reject/:id", to: "charities#reject"
  get '/charitydetails/:id', to: 'charities#show'
  get '/charities', to: 'charities#index'
  post '/charity/signup', to: 'charities#create'

  get 'beneficiaries', to: 'charities#beneficiaries'
  get 'charitydetails', to: 'charities#beneficiaries'
  post 'beneficiaries', to: 'charities#create_beneficiary'
  put 'beneficiaries/:beneficiary_id', to: 'charities#update_beneficiary'
  delete 'beneficiaries/:beneficiary_id', to: 'charities#destroy_beneficiary'


  #DONOR ROUTES
  post '/donor/signup', to: 'donors#create'
  get '/donor/signup', to: 'donors#new'

  post '/donor/login', to: 'donors#login'
  get '/charities', to: 'donors#charities'
  get '/charities/:id', to: 'donors#show_charity'
  post '/donations', to: 'donors#donate'
  post '/donations/automate', to: 'donors#automate_donation'
  post '/donations/cancel', to: 'donors#cancel_donation'
  get '/beneficiaries', to: 'donors#beneficiaries'
  post '/donations/paypal', to: 'donors#paypal'
  post '/donations/stripe', to: 'donors#stripe'

   # Administrator routes
   post '/administrator/login', to: 'administrators#login'
   get '/administrator/applications', to: 'administrators#applications'
   post '/administrator/applications/:id/approve', to: 'administrators#approve_application'
   post '/administrator/applications/:id/reject', to: 'administrators#reject_application'
   delete '/administrator/charities/:id', to: 'administrators#delete_charity'
   get '/charities/unapproved', to: 'charities#unapproved'
   get '/charities/approved', to: 'charities#approved'
   


   # Donations routes
   get '/donations', to: 'donations#index'
   post '/donations', to: 'donations#create'
   get '/donations/:id', to: 'donations#show'
   put '/donations/:id', to: 'donations#update'
   delete '/donations/:id', to: 'donations#destroy'

  #  Application Routes
  # Contact Us Form Route
  post "/contact-us", to: 'application#contact_us'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Backend/app/models/donor.rb
class Donor < ApplicationRecord
    has_secure_password
    has_many :donations
    has_many :charities, through: :donations
end

Backend/app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  # skip_before_action :authorize, only: [ :create]
  before_action :authorize_request, only: [ :donate, :set_donation_reminder]
 

  def index
    donors = Donor.all
    render json: { donors: donors }, status: :ok
  end
  

  def create
    donor = Donor.create(donor_params)
    if donor.save
      DonorNotifierMailer.send_donor_signup_email(donor).deliver_now

      render json: { message: 'Donor created successfully' }, status: :created
    else
      render json: { error: 'Unable to create donor' }, status: :unprocessable_entity
    end
  end

  def donate
    charity = Charity.find(params[:charity_id])
    donation = Donation.create(donation_params)
    if donation.save
      render json: { message: 'Donation made successfully' }, status: :created
    else
      render json: { error: 'Unable to make donation' }, status: :unprocessable_entity
    end
  end

  def set_donation_reminder
    reminder = Reminder.create(reminder_params)
    if reminder.save
      render json: { message: 'Donation reminder set successfully' }, status: :created
    else
      render json: { error: 'Unable to set donation reminder' }, status: :unprocessable_entity
    end
  end

  private

  def donor_params
    params.permit(:first_name, :last_name, :email, :password)
  end
  

  def donation_params
    params.permit(:amount, :charity_id, :anonymous, :payment_method)
  end

  def reminder_params
    params.permit(:donor_id, :reminder_time)
  end

  def authorize_request
    header = request.headers['Authorization']
    token = header.split(' ').last if header
    begin
      @decoded = JsonWebToken.decode(token)
      @current_donor = Donor.find(@decoded[:id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.message }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { errors: e.message }, status: :unauthorized
    end
  end
end

Backend/app/helpers/donors_helper.rb
module DonorsHelper
end

Backend/app/views/donors/_donor.html.erb
<div id="<%= dom_id donor %>">
  <p>
    <strong>First name:</strong>
    <%= donor.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= donor.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= donor.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= donor.password %>
  </p>

</div>

Backend/app/views/donors/_form.html.erb
<%= form_with(model: donor) do |form| %>
  <% if donor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
        <% donor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Backend/app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render "form", donor: @donor %>

<br>

<div>
  <%= link_to "Show this donor", @donor %> |
  <%= link_to "Back to donors", donors_path %>
</div>

Backend/app/views/donors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Donors</h1>

<div id="donors">
  <% @donors.each do |donor| %>
    <%= render donor %>
    <p>
      <%= link_to "Show this donor", donor %>
    </p>
  <% end %>
</div>

<%= link_to "New donor", new_donor_path %>

Backend/app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render "form", donor: @donor %>

<br>

<div>
  <%= link_to "Back to donors", donors_path %>
</div>

Backend/app/views/donors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @donor %>

<div>
  <%= link_to "Edit this donor", edit_donor_path(@donor) %> |
  <%= link_to "Back to donors", donors_path %>

  <%= button_to "Destroy this donor", @donor, method: :delete %>
</div>